"""Debug script: prints the full graph structure generated by graph_server.py"""
import sys
sys.path.insert(0, '.')
import random
from collections import defaultdict, deque

# Reproduce exactly what graph_server.py does
random.seed(42)

def generate_transactions():
    transactions = []
    tx_id = 0
    all_nodes = set()

    num_clean_chains = random.randint(5, 7)
    print(f"Generating {num_clean_chains} clean chains...")
    for chain_idx in range(num_clean_chains):
        chain_length = random.randint(3, 5)
        print(f"  Clean chain {chain_idx}: length={chain_length}")
        for step in range(chain_length - 1):
            from_addr = f"0xclean{chain_idx:02d}_{step:02d}{''.join(random.choices('0123456789abcdef', k=4))}"
            to_addr = f"0xclean{chain_idx:02d}_{step+1:02d}{''.join(random.choices('0123456789abcdef', k=4))}"
            all_nodes.add(from_addr)
            all_nodes.add(to_addr)
            transactions.append({'from_address': from_addr, 'to_address': to_addr, 'from_scam': 0, 'tx_id': tx_id})
            tx_id += 1

    num_hacks = random.randint(1, 2)
    print(f"\nGenerating {num_hacks} hack chains...")
    for hack_idx in range(num_hacks):
        hack_source = f"0xhack{hack_idx}{''.join(random.choices('0123456789abcdef', k=8))}"
        hack_chain_length = random.randint(3, 4)
        print(f"  Hack chain {hack_idx}: source={hack_source[:20]}, length={hack_chain_length}")
        current = hack_source
        for step in range(hack_chain_length):
            next_node = f"0xvic{hack_idx}_{step}{''.join(random.choices('0123456789abcdef', k=6))}"
            all_nodes.add(current)
            all_nodes.add(next_node)
            transactions.append({'from_address': current, 'to_address': next_node, 'from_scam': 1 if step == 0 else 0, 'tx_id': tx_id})
            tx_id += 1
            current = next_node

    while len(transactions) < 100 and all_nodes:
        from_addr = random.choice(list(all_nodes))
        to_addr = f"0xuser{''.join(random.choices('0123456789abcdef', k=10))}"
        all_nodes.add(from_addr)
        all_nodes.add(to_addr)
        transactions.append({'from_address': from_addr, 'to_address': to_addr, 'from_scam': 0, 'tx_id': tx_id})
        tx_id += 1

    return transactions[:100]

txs = generate_transactions()
print(f"\nTotal transactions: {len(txs)}")

# Build graph
nodes = set()
edges = []
out_edges = defaultdict(list)
in_edges = defaultdict(list)

for tx in txs:
    f = tx['from_address']
    t = tx['to_address']
    nodes.add(f)
    nodes.add(t)
    edges.append((f, t))
    out_edges[f].append(t)
    in_edges[t].append(f)

print(f"Total unique nodes: {len(nodes)}")
print(f"Total edges: {len(edges)}")

# Count isolated nodes
isolated = [n for n in nodes if len(out_edges[n]) == 0 and len(in_edges[n]) == 0]
print(f"Isolated nodes (no edges at all): {len(isolated)}")

# Show degree distribution
degrees = [(n, len(out_edges[n]), len(in_edges[n])) for n in nodes]
degrees.sort(key=lambda x: -(x[1]+x[2]))
print("\n=== TOP 15 MOST CONNECTED NODES ===")
for addr, out, inp in degrees[:15]:
    print(f"  {addr[:25]}  out={out}  in={inp}")

# Show all clean chains
print("\n=== CHAIN STRUCTURE ===")
roots = [n for n in nodes if len(in_edges[n]) == 0]
print(f"Root nodes (no incoming): {len(roots)}")
for r in roots[:10]:
    chain = [r]
    current = r
    visited = set([r])
    while out_edges[current]:
        next_n = out_edges[current][0]
        if next_n in visited:
            break
        chain.append(next_n)
        visited.add(next_n)
        current = next_n
    print(f"  Chain: {' -> '.join(n[:12] for n in chain)}")
